'use client';

import { useState } from 'react';
import Link from 'next/link';
import { Activity, ArrowLeft, ArrowUpRight, Ban, Boxes, Building2, Check, CheckCircle2, CircleDot, Clock3, Code2, Cpu, Database, Download, FlaskConical, GitBranch, Layers3, MapPin, Radio, Server, ShieldCheck, SlidersHorizontal, TerminalSquare, Thermometer, Workflow, X, Zap } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { buttonVariants } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';

type View = 'infrastructure' | 'flow' | 'overview' | 'finetuning' | 'evals' | 'traces';
type InfrastructureScope = 'center' | 'hall' | 'row';
type InfrastructureRow = { id: string; name: string; racks: number; utilization: number; temperature: number; power: number; pue: number; latency: number; workloads: number; status: 'healthy' | 'watch' };
type InfrastructureHall = { id: string; name: string; rows: InfrastructureRow[] };
type InfrastructureCenter = { id: string; name: string; region: string; halls: InfrastructureHall[] };

const repo = 'https://github.com/sivalinb/ultramedia-studio';
const evidence = {
  index: `${repo}/blob/main/docs/OBSERVABILITY_EVIDENCE.md`,
  snapshot: `${repo}/blob/main/public/data/model-observability.json`,
  trainingData: `${repo}/blob/main/backend/scripts/prepare_training_data.py#L14-L69`,
  qlora: `${repo}/blob/main/backend/scripts/train_qlora.py#L5-L71`,
  merge: `${repo}/blob/main/backend/scripts/merge_adapter.py#L5-L19`,
  ollama: `${repo}/blob/main/backend/Modelfile#L1-L4`,
  evals: `${repo}/blob/main/backend/src/ultramedia/evals.py#L10-L75`,
  tests: `${repo}/blob/main/backend/tests/test_api.py#L1-L85`,
  workflow: `${repo}/blob/main/backend/src/ultramedia/workflow.py#L26-L152`,
  traceRecorder: `${repo}/blob/main/backend/src/ultramedia/observability.py#L15-L65`,
  provider: `${repo}/blob/main/backend/src/ultramedia/providers.py#L37-L81`,
  retrieval: `${repo}/blob/main/backend/src/ultramedia/retrieval.py#L25-L73`,
  modelCard: `${repo}/blob/main/docs/MODEL_CARD.md`,
  deployment: `${repo}/blob/main/docs/DEPLOYMENT.md`,
  qwenLicense: 'https://huggingface.co/Qwen/Qwen3-4B-Instruct-2507',
  infrastructure: `${repo}/blob/main/public/data/datacenter-telemetry.json`,
};

const infrastructureSites: InfrastructureCenter[] = [
  { id: 'den-01', name: 'Denver Edge 01', region: 'US Mountain', halls: [
    { id: 'hall-a', name: 'Hall A · Live inference', rows: [
      { id: 'a1', name: 'A1 · GPU inference', racks: 12, utilization: 68, temperature: 22.4, power: 142, pue: 1.21, latency: 18, workloads: 42, status: 'healthy' },
      { id: 'a2', name: 'A2 · Retrieval', racks: 10, utilization: 54, temperature: 21.9, power: 108, pue: 1.19, latency: 12, workloads: 31, status: 'healthy' },
      { id: 'a3', name: 'A3 · Model serving', racks: 14, utilization: 76, temperature: 23.8, power: 178, pue: 1.24, latency: 24, workloads: 55, status: 'watch' },
    ] },
    { id: 'hall-b', name: 'Hall B · Training lab', rows: [
      { id: 'b1', name: 'B1 · QLoRA sandbox', racks: 8, utilization: 38, temperature: 21.6, power: 84, pue: 1.18, latency: 16, workloads: 12, status: 'healthy' },
      { id: 'b2', name: 'B2 · Evaluation', racks: 10, utilization: 63, temperature: 24.8, power: 126, pue: 1.27, latency: 21, workloads: 27, status: 'watch' },
      { id: 'b3', name: 'B3 · Cold standby', racks: 8, utilization: 12, temperature: 20.7, power: 36, pue: 1.16, latency: 14, workloads: 4, status: 'healthy' },
    ] },
  ] },
  { id: 'pdx-02', name: 'Portland Core 02', region: 'US West', halls: [
    { id: 'hall-c', name: 'Hall C · Production', rows: [
      { id: 'c1', name: 'C1 · Primary models', racks: 16, utilization: 72, temperature: 22.9, power: 196, pue: 1.22, latency: 20, workloads: 61, status: 'healthy' },
      { id: 'c2', name: 'C2 · Vector search', racks: 12, utilization: 66, temperature: 23.1, power: 151, pue: 1.23, latency: 15, workloads: 48, status: 'healthy' },
      { id: 'c3', name: 'C3 · Media pipeline', racks: 14, utilization: 81, temperature: 25.1, power: 204, pue: 1.29, latency: 29, workloads: 68, status: 'watch' },
    ] },
    { id: 'hall-d', name: 'Hall D · Resilience', rows: [
      { id: 'd1', name: 'D1 · Failover', racks: 10, utilization: 22, temperature: 20.9, power: 57, pue: 1.17, latency: 19, workloads: 8, status: 'healthy' },
      { id: 'd2', name: 'D2 · Archive', racks: 12, utilization: 44, temperature: 21.3, power: 91, pue: 1.18, latency: 31, workloads: 19, status: 'healthy' },
      { id: 'd3', name: 'D3 · Recovery', racks: 10, utilization: 31, temperature: 21.8, power: 69, pue: 1.18, latency: 23, workloads: 11, status: 'healthy' },
    ] },
  ] },
];

const evals = [
  { name: 'Retrieval recall @3', score: 100, target: '≥ 75%', note: '4/4 expected evidence records retrieved', href: `${repo}/blob/main/backend/src/ultramedia/evals.py#L10-L23` },
  { name: 'Citation validity', score: 100, target: '= 100%', note: 'Every generated draft carried citations', href: `${repo}/blob/main/backend/src/ultramedia/evals.py#L24-L56` },
  { name: 'Human review gate', score: 100, target: '= 100%', note: 'Every draft stopped at pending review', href: `${repo}/blob/main/backend/src/ultramedia/evals.py#L37-L62` },
  { name: 'Unsupported sensitive inference', score: 0, target: '= 0%', note: 'No invented injury, collapse, or dehydration claim', inverse: true, href: `${repo}/blob/main/backend/src/ultramedia/evals.py#L40-L67` },
];

const trace = [
  { stage: 'moment_detector', duration: 1, detail: 'Validated race signal and athlete reference', href: `${repo}/blob/main/backend/src/ultramedia/workflow.py#L54-L59` },
  { stage: 'evidence_retriever', duration: 2, detail: 'Hybrid retrieval over timing and course context', href: `${repo}/blob/main/backend/src/ultramedia/workflow.py#L61-L82` },
  { stage: 'story_writer', duration: 1, detail: 'Generated structured draft with local-deterministic', href: `${repo}/blob/main/backend/src/ultramedia/workflow.py#L84-L87` },
  { stage: 'fact_verifier', duration: 1, detail: 'Checked citations and claim support', href: `${repo}/blob/main/backend/src/ultramedia/workflow.py#L89-L98` },
  { stage: 'safety_editor', duration: 1, detail: 'Blocked unsupported health and intent inferences', href: `${repo}/blob/main/backend/src/ultramedia/workflow.py#L100-L108` },
  { stage: 'human_review_queue', duration: 1, detail: 'Stored draft as pending; no automatic publication', href: `${repo}/blob/main/backend/src/ultramedia/workflow.py#L110-L132` },
];

const methods = [
  { icon: <Database />, number: '01', title: 'Approval-only dataset', body: 'Only editor-approved story drafts can enter training. Each example retains the evidence IDs used to support its claims.', facts: ['Minimum 20 examples', '90 / 10 train-validation split', 'Deterministic seed · 42'], href: evidence.trainingData },
  { icon: <Boxes />, number: '02', title: '4-bit QLoRA', body: 'The 4B base model is loaded in NF4 with double quantization. Low-rank weights are trained while the quantized base remains frozen.', facts: ['NF4 · double quantization', 'bfloat16 compute', 'Lower GPU memory'], href: evidence.qlora },
  { icon: <SlidersHorizontal />, number: '03', title: 'LoRA adapters', body: 'Rank-16 adapters target attention and MLP projections so the model learns newsroom structure without relearning race facts.', facts: ['r 16 · alpha 32', 'Dropout 0.05', 'q/k/v/o + gate/up/down'], href: evidence.qlora },
  { icon: <Code2 />, number: '04', title: 'Supervised tuning', body: 'TRL’s SFT trainer teaches headline discipline, citation placement, abstention, and channel-ready JSON formatting.', facts: ['2 epochs', 'LR 2e-4 · warmup 5%', 'Effective batch size 16'], href: evidence.qlora },
  { icon: <GitBranch />, number: '05', title: 'Merge and package', body: 'PEFT merges a passing adapter into Qwen3. The merged model can then be converted to GGUF and served locally through Ollama.', facts: ['Safe tensors', 'GGUF conversion path', 'Local-first inference'], href: evidence.merge },
];

const liveFlow = [
  { number: '01', title: 'Moment detected', detail: 'Validate timing signal', metric: 'INPUT', visual: 'signal' as const, icon: <Radio />, state: 'active' as const, href: `${repo}/blob/main/backend/src/ultramedia/workflow.py#L54-L59` },
  { number: '02', title: 'Hybrid RAG', detail: 'Retrieve top evidence', metric: 'R@3 100%', visual: 'rag' as const, icon: <Database />, state: 'pass' as const, href: evidence.retrieval },
  { number: '03', title: 'Story generated', detail: 'Structured cited draft', metric: 'LOCAL', visual: 'writer' as const, icon: <Workflow />, state: 'pass' as const, href: `${repo}/blob/main/backend/src/ultramedia/workflow.py#L84-L87` },
  { number: '04', title: 'Facts + safety', detail: 'Citations and sensitive claims', metric: 'PASS', visual: 'safety' as const, icon: <ShieldCheck />, state: 'pass' as const, href: `${repo}/blob/main/backend/src/ultramedia/workflow.py#L89-L108` },
  { number: '05', title: 'Human queue', detail: 'Approve or revise', metric: 'PENDING', visual: 'review' as const, icon: <CheckCircle2 />, state: 'pass' as const, href: `${repo}/blob/main/backend/src/ultramedia/workflow.py#L110-L132` },
];

const trainingFlow = [
  { number: '01', title: 'Approved edits', detail: 'Evidence-linked examples', metric: '0 READY', visual: 'approved' as const, icon: <CheckCircle2 />, state: 'active' as const, href: evidence.trainingData },
  { number: '02', title: 'Dataset gate', detail: 'Minimum 20 required', metric: 'BLOCKED', visual: 'gate' as const, icon: <Ban />, state: 'gated' as const, href: evidence.trainingData },
  { number: '03', title: 'QLoRA train', detail: '4-bit adapter tuning', metric: 'WAITING', visual: 'qlora' as const, icon: <SlidersHorizontal />, state: 'waiting' as const, href: evidence.qlora },
  { number: '04', title: 'Challenger eval', detail: 'Compare with RAG', metric: 'WAITING', visual: 'eval' as const, icon: <FlaskConical />, state: 'waiting' as const, href: evidence.modelCard },
  { number: '05', title: 'Merge + serve', detail: 'PEFT → GGUF → Ollama', metric: 'WAITING', visual: 'serve' as const, icon: <Server />, state: 'waiting' as const, href: evidence.merge },
];

export default function ObservabilityPage() {
  const [view, setView] = useState<View>('infrastructure');
  return (
    <main className="min-h-screen bg-[#080b09] text-foreground">
      <header className="sticky top-0 z-50 border-b border-white/10 bg-[#080b09]/95 backdrop-blur-xl">
        <div className="mx-auto flex h-16 max-w-[1600px] items-center justify-between px-4 sm:px-6">
          <div className="flex items-center gap-3"><Link href="/" className={buttonVariants({ variant: 'ghost', size: 'icon-sm', className: 'rounded-full' })} aria-label="Back to UltraMedia home"><ArrowLeft className="size-4" /></Link><span className="grid size-8 place-items-center rounded-full bg-primary text-primary-foreground"><Activity className="size-4" /></span><div><p className="text-xs font-black">ULTRAMEDIA <span className="text-white/40">MODEL OPS</span></p><p className="text-[9px] uppercase tracking-[.15em] text-white/30">Evidence console</p></div></div>
          <div className="hidden items-center gap-5 text-xs font-semibold text-white/40 md:flex"><Link href="/races" className="hover:text-white">Race atlas</Link><Link href="/studio" className="hover:text-white">Newsroom</Link><span className="text-primary">Observability</span></div>
          <a href={evidence.index + '#verification-snapshot'} target="_blank" rel="noreferrer" aria-label="Open evidence for the Base plus RAG pass status"><Badge variant="outline" className="border-emerald-300/20 bg-emerald-300/5 text-emerald-300"><span className="mr-2 size-1.5 rounded-full bg-emerald-300" /> Base + RAG · PASS <ArrowUpRight className="ml-1 size-3" /></Badge></a>
        </div>
      </header>

      <div className="mx-auto max-w-[1600px] px-4 py-5 sm:px-6">
        <section className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_340px]">
          <div className="relative overflow-hidden rounded-2xl border border-white/10 bg-[#0d120f] p-6 sm:p-8">
            <div className="absolute inset-0 bg-[radial-gradient(circle_at_85%_0%,rgba(196,255,74,.12),transparent_35%)]" />
            <div className="relative flex flex-col justify-between gap-10 lg:flex-row lg:items-end"><div><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.2em] text-primary"><Radio className="size-3" /> Model release observability</div><h1 className="mt-4 text-4xl font-black uppercase leading-[.9] tracking-[-.055em] sm:text-6xl">What was built.<br /><span className="text-white/35">What actually ran.</span></h1><p className="mt-5 max-w-2xl text-sm leading-7 text-white/45">A truthful operational view of UltraMedia’s fine-tuning path, measured evaluation results, model decision, and agent execution—not a simulated training report.</p><div className="mt-4 flex flex-wrap gap-2"><EvidenceLink href={evidence.index} label="Claim evidence register" /><EvidenceLink href={evidence.snapshot} label="Machine-readable snapshot" /></div></div><div className="flex shrink-0 gap-2"><a href="/data/model-observability.json" download className={buttonVariants({ variant: 'outline', className: 'rounded-full border-white/15' })}><Download className="size-4" /> Export snapshot</a><Link href="/studio" className={buttonVariants({ className: 'rounded-full font-bold' })}>Open newsroom <ArrowUpRight className="size-4" /></Link></div></div>
          </div>
          <div className="rounded-2xl border border-amber-300/20 bg-amber-300/[.04] p-6"><div className="flex items-center justify-between"><div className="flex items-center gap-2 text-amber-200"><Ban className="size-4" /><p className="text-[10px] font-bold uppercase tracking-[.16em]">Training gate</p></div><Badge variant="outline" className="border-amber-300/20 text-amber-200">BLOCKED BY DESIGN</Badge></div><p className="mt-7 font-mono text-5xl font-semibold text-amber-200">0<span className="text-xl text-white/25"> / 20</span></p><p className="mt-2 text-xs text-white/40">Human-approved examples available</p><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-white/8"><div className="h-full w-0 bg-amber-200" /></div><p className="mt-4 text-[10px] leading-5 text-white/35">QLoRA training was not run and no adapter result is claimed. The guard prevents tuning on unreviewed synthetic drafts.</p><div className="mt-4 flex flex-wrap gap-2"><EvidenceLink href={evidence.index + '#verification-snapshot'} label="Observed count" /><EvidenceLink href={evidence.trainingData} label="Gate implementation" /></div></div>
        </section>

        <nav className="mt-4 flex gap-1 overflow-x-auto rounded-xl border border-white/10 bg-[#0d120f] p-1" aria-label="Observability views">
          <NavTab active={view === 'infrastructure'} onClick={() => setView('infrastructure')} icon={<Building2 />} label="Data center twin" />
          <NavTab active={view === 'flow'} onClick={() => setView('flow')} icon={<Workflow />} label="Live system flow" />
          <NavTab active={view === 'overview'} onClick={() => setView('overview')} icon={<CircleDot />} label="Overview" />
          <NavTab active={view === 'finetuning'} onClick={() => setView('finetuning')} icon={<SlidersHorizontal />} label="Fine-tuning method" />
          <NavTab active={view === 'evals'} onClick={() => setView('evals')} icon={<FlaskConical />} label="Measured evals" />
          <NavTab active={view === 'traces'} onClick={() => setView('traces')} icon={<Workflow />} label="Agent traces" />
          <a href={evidence.index + '#verification-snapshot'} target="_blank" rel="noreferrer" className="ml-auto hidden items-center gap-2 px-3 font-mono text-[9px] text-white/25 transition hover:text-primary md:flex"><Clock3 className="size-3" /> Snapshot · Sep 6, 2026 <ArrowUpRight className="size-2.5" /></a>
        </nav>

        {view === 'infrastructure' && <DataCenterTwin />}
        {view === 'flow' && <SystemFlow />}
        {view === 'overview' && <Overview />}
        {view === 'finetuning' && <FineTuning />}
        {view === 'evals' && <Evals />}
        {view === 'traces' && <Traces />}

        <footer className="mt-5 flex flex-col justify-between gap-4 border-t border-white/10 py-7 text-xs text-white/30 sm:flex-row"><p>UltraMedia Model Ops · every displayed claim links to implementation, run evidence, or an explicit evidence boundary</p><div className="flex flex-wrap gap-5"><a href={evidence.index} target="_blank" rel="noreferrer" className="hover:text-primary">Evidence register</a><a href={evidence.modelCard} target="_blank" rel="noreferrer" className="hover:text-primary">Model card</a><a href={`${repo}/tree/main/backend/scripts`} target="_blank" rel="noreferrer" className="hover:text-primary">Training code</a></div></footer>
      </div>
    </main>
  );
}

function DataCenterTwin() {
  const [scope, setScope] = useState<InfrastructureScope>('center');
  const [centerId, setCenterId] = useState(infrastructureSites[0].id);
  const center = infrastructureSites.find((item) => item.id === centerId) ?? infrastructureSites[0];
  const [hallId, setHallId] = useState(center.halls[0].id);
  const hall = center.halls.find((item) => item.id === hallId) ?? center.halls[0];
  const [rowId, setRowId] = useState(hall.rows[0].id);
  const row = hall.rows.find((item) => item.id === rowId) ?? hall.rows[0];
  const visibleRows = scope === 'center' ? center.halls.flatMap((item) => item.rows) : scope === 'hall' ? hall.rows : [row];
  const racks = visibleRows.reduce((sum, item) => sum + item.racks, 0);
  const power = visibleRows.reduce((sum, item) => sum + item.power, 0);
  const workloads = visibleRows.reduce((sum, item) => sum + item.workloads, 0);
  const utilization = Math.round(visibleRows.reduce((sum, item) => sum + item.utilization, 0) / visibleRows.length);
  const temperature = (visibleRows.reduce((sum, item) => sum + item.temperature, 0) / visibleRows.length).toFixed(1);
  const pue = (visibleRows.reduce((sum, item) => sum + item.pue, 0) / visibleRows.length).toFixed(2);
  const watchRows = visibleRows.filter((item) => item.status === 'watch');

  function changeCenter(value: string | null) {
    if (!value) return;
    const nextCenter = infrastructureSites.find((item) => item.id === value) ?? infrastructureSites[0];
    setCenterId(nextCenter.id);
    setHallId(nextCenter.halls[0].id);
    setRowId(nextCenter.halls[0].rows[0].id);
  }

  function changeHall(value: string | null) {
    if (!value) return;
    const nextHall = center.halls.find((item) => item.id === value) ?? center.halls[0];
    setHallId(nextHall.id);
    setRowId(nextHall.rows[0].id);
  }

  return <div className="mt-4 space-y-4">
    <section className="rounded-2xl border border-cyan-300/15 bg-[#0b1111] p-4 sm:p-6">
      <div className="flex flex-col justify-between gap-5 xl:flex-row xl:items-end">
        <div><div className="flex items-center gap-2 text-sm font-bold uppercase tracking-[.16em] text-cyan-300"><span className="size-2 animate-pulse rounded-full bg-cyan-300" /> Infrastructure digital twin</div><h2 className="mt-2 text-2xl font-black uppercase tracking-[-.03em] sm:text-4xl">Zoom from campus to rack row</h2><p className="mt-3 max-w-3xl text-base leading-7 text-white/50">Explore where UltraMedia workloads would run, then isolate capacity, thermal, power, and health signals at each physical level.</p></div>
        <div className="flex flex-wrap items-center gap-2"><Badge variant="outline" className="h-8 border-cyan-300/20 bg-cyan-300/[.05] px-3 text-xs text-cyan-200">PORTFOLIO DEMO TELEMETRY</Badge><EvidenceLink href={evidence.infrastructure} label="Open demo dataset" /></div>
      </div>

      <div className="mt-6 grid gap-3 lg:grid-cols-3">
        <div className="space-y-2"><label htmlFor="infrastructure-center" className="flex items-center gap-2 text-sm font-semibold text-white/55"><MapPin className="size-4 text-cyan-300" /> Data center</label><Select value={center.id} onValueChange={changeCenter}><SelectTrigger id="infrastructure-center" className="h-11 w-full border-white/10 bg-black/20 px-3"><SelectValue /></SelectTrigger><SelectContent>{infrastructureSites.map((item) => <SelectItem key={item.id} value={item.id}>{item.name} · {item.region}</SelectItem>)}</SelectContent></Select></div>
        <div className="space-y-2"><label htmlFor="infrastructure-hall" className="flex items-center gap-2 text-sm font-semibold text-white/55"><Building2 className="size-4 text-cyan-300" /> Data hall</label><Select value={hall.id} onValueChange={changeHall}><SelectTrigger id="infrastructure-hall" className="h-11 w-full border-white/10 bg-black/20 px-3"><SelectValue /></SelectTrigger><SelectContent>{center.halls.map((item) => <SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select></div>
        <div className="space-y-2"><label htmlFor="infrastructure-row" className="flex items-center gap-2 text-sm font-semibold text-white/55"><Server className="size-4 text-cyan-300" /> Rack row</label><Select value={row.id} onValueChange={(value) => value && setRowId(value)}><SelectTrigger id="infrastructure-row" className="h-11 w-full border-white/10 bg-black/20 px-3"><SelectValue /></SelectTrigger><SelectContent>{hall.rows.map((item) => <SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select></div>
      </div>
    </section>

    <section className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_360px]">
      <div className="overflow-hidden rounded-2xl border border-cyan-300/15 bg-[#080d0e]">
        <div className="flex flex-col gap-4 border-b border-white/8 p-4 sm:flex-row sm:items-center sm:justify-between sm:px-6">
          <div><p className="text-sm font-semibold text-white">{scope === 'center' ? center.name : scope === 'hall' ? hall.name : row.name}</p><p className="mt-1 text-xs text-white/35">{center.region} · {scope === 'center' ? `${center.halls.length} halls` : scope === 'hall' ? `${hall.rows.length} rows` : `${row.racks} racks`}</p></div>
          <fieldset className="flex w-fit rounded-xl border border-white/10 bg-black/30 p-1"><legend className="sr-only">Digital twin camera level</legend><ScopeButton active={scope === 'center'} onClick={() => setScope('center')} label="Center" /><ScopeButton active={scope === 'hall'} onClick={() => setScope('hall')} label="Hall" /><ScopeButton active={scope === 'row'} onClick={() => setScope('row')} label="Row" /></fieldset>
        </div>
        <DataCenterScene scope={scope} center={center} hall={hall} row={row} />
        <div className="grid grid-cols-2 gap-px border-t border-white/8 bg-white/8 sm:grid-cols-3 xl:grid-cols-6"><InfrastructureMetric icon={<Cpu />} value={`${utilization}%`} label="Compute" /><InfrastructureMetric icon={<Thermometer />} value={`${temperature}°C`} label="Intake" warn={Number(temperature) >= 24.5} /><InfrastructureMetric icon={<Zap />} value={`${power} kW`} label="IT load" /><InfrastructureMetric icon={<Activity />} value={pue} label="PUE" /><InfrastructureMetric icon={<Server />} value={`${racks}`} label="Racks" /><InfrastructureMetric icon={<Workflow />} value={`${workloads}`} label="Workloads" /></div>
      </div>

      <aside className="space-y-4">
        <section className="rounded-2xl border border-white/10 bg-[#0d120f] p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-cyan-300">Scope health</p><h3 className="mt-2 text-xl font-semibold">{watchRows.length ? `${watchRows.length} item${watchRows.length > 1 ? 's' : ''} to watch` : 'All systems nominal'}</h3></div><span className={`grid size-10 place-items-center rounded-full ${watchRows.length ? 'bg-amber-200/10 text-amber-200' : 'bg-emerald-300/10 text-emerald-300'}`}>{watchRows.length ? <Thermometer className="size-5" /> : <CheckCircle2 className="size-5" />}</span></div><div className="mt-5 space-y-2">{visibleRows.map((item) => <button key={item.id} type="button" aria-label={`Inspect ${item.name} in row view`} onClick={() => { const parentHall = center.halls.find((candidate) => candidate.rows.some((candidateRow) => candidateRow.id === item.id)); if (parentHall) setHallId(parentHall.id); setRowId(item.id); setScope('row'); }} className="flex w-full items-center justify-between rounded-xl border border-white/8 bg-white/[.02] p-3 text-left transition hover:border-cyan-300/30 hover:bg-cyan-300/[.04]"><span><span className="block text-sm font-semibold">{item.name}</span><span className="mt-1 block text-xs text-white/35">{item.utilization}% compute · {item.temperature}°C</span></span><span aria-hidden="true" className={`size-2.5 rounded-full ${item.status === 'watch' ? 'bg-amber-200 shadow-[0_0_12px_#fde68a]' : 'bg-emerald-300 shadow-[0_0_12px_#6ee7b7]'}`} /></button>)}</div></section>
        <section className="rounded-2xl border border-cyan-300/15 bg-cyan-300/[.03] p-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-cyan-300">Workload placement</p><div className="mt-5 space-y-4"><CapacityBar label="Inference agents" value={Math.min(88, utilization + 8)} /><CapacityBar label="Vector retrieval" value={Math.max(24, utilization - 14)} /><CapacityBar label="Evaluation jobs" value={Math.max(12, Math.round(utilization / 2))} /></div><p className="mt-5 text-xs leading-5 text-white/35">Synthetic operational values demonstrate the filtering and digital-twin experience; they are not readings from deployed hardware.</p></section>
      </aside>
    </section>
  </div>;
}

function ScopeButton({ active, onClick, label }: { active: boolean; onClick: () => void; label: string }) { return <button type="button" onClick={onClick} aria-pressed={active} className={`rounded-lg px-4 py-2 text-sm font-semibold transition ${active ? 'bg-cyan-300 text-[#061012]' : 'text-white/45 hover:text-white'}`}>{label}</button>; }

function InfrastructureMetric({ icon, value, label, warn = false }: { icon: React.ReactNode; value: string; label: string; warn?: boolean }) { return <div className="bg-[#0b1111] p-4"><span className={`[&>svg]:size-4 ${warn ? 'text-amber-200' : 'text-cyan-300'}`}>{icon}</span><p className={`mt-3 font-mono text-lg ${warn ? 'text-amber-200' : 'text-white'}`}>{value}</p><p className="mt-1 text-xs text-white/35">{label}</p></div>; }

function CapacityBar({ label, value }: { label: string; value: number }) { return <div><div className="flex items-center justify-between text-sm"><span className="text-white/55">{label}</span><span className="font-mono text-cyan-200">{value}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/8"><div className="h-full rounded-full bg-gradient-to-r from-cyan-500 to-primary" style={{ width: `${value}%` }} /></div></div>; }

function DataCenterScene({ scope, center, hall, row }: { scope: InfrastructureScope; center: InfrastructureCenter; hall: InfrastructureHall; row: InfrastructureRow }) {
  return <div className={`dc-scene dc-scene-${scope}`} aria-label={`Animated 3D ${scope} view for ${scope === 'center' ? center.name : scope === 'hall' ? hall.name : row.name}`}>
    <div className="dc-horizon" aria-hidden="true" />
    <div className="dc-camera" aria-hidden="true">
      {scope === 'center' && <div className="dc-campus"><div className="dc-campus-road" />{center.halls.map((item, index) => <div key={item.id} className={`dc-building dc-building-${index + 1}`}><span className="dc-cube-top" /><span className="dc-cube-side" /><span className="dc-cube-front"><Building2 /><b>{item.id.toUpperCase()}</b><small>{item.rows.length} rows</small></span></div>)}<div className="dc-power-ring"><span /><span /><span /></div></div>}
      {scope === 'hall' && <div className="dc-hall"><div className="dc-cooling-rail dc-cooling-left" /><div className="dc-cooling-rail dc-cooling-right" /><div className="dc-aisle-floor" />{hall.rows.map((item, index) => <div key={item.id} className={`dc-row-bank dc-row-bank-${index + 1}`}><div className="dc-rack-face">{Array.from({ length: 7 }).map((_, light) => <i key={light} style={{ animationDelay: `${(index * 7 + light) * .09}s` }} />)}</div><span>{item.id.toUpperCase()}</span></div>)}</div>}
      {scope === 'row' && <div className="dc-row"><div className="dc-row-floor" />{Array.from({ length: Math.min(row.racks, 12) }).map((_, index) => <div key={index} className={`dc-rack dc-rack-${index + 1} ${row.status === 'watch' && index === 7 ? 'dc-rack-watch' : ''}`}><span className="dc-rack-top" /><span className="dc-rack-side" /><span className="dc-rack-front">{Array.from({ length: 9 }).map((__, light) => <i key={light} style={{ animationDelay: `${(index + light) * .08}s` }} />)}</span><b>R{String(index + 1).padStart(2, '0')}</b></div>)}<div className="dc-packet-stream">{Array.from({ length: 5 }).map((_, index) => <i key={index} style={{ animationDelay: `${index * .45}s` }} />)}</div></div>}
    </div>
    <div className="dc-scene-hud"><span>LIVE DIGITAL TWIN</span><span>{scope.toUpperCase()} CAMERA · AUTO ORBIT</span></div>
  </div>;
}

function SystemFlow() {
  const [focus, setFocus] = useState<'live' | 'training'>('live');
  return <div className="mt-4 space-y-4">
    <section className="ops-cinema relative min-h-[250px] overflow-hidden rounded-2xl border border-white/10 bg-[#0d120f] p-5 sm:p-7">
      <div className="ops-cinema-grid" aria-hidden="true" /><div className="ops-cinema-scan" aria-hidden="true" /><div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-primary/70 to-transparent" />
      <div className="relative z-10 flex items-center justify-between border-b border-white/8 pb-4 font-mono text-[8px] uppercase tracking-[.16em] text-white/25"><span className="flex items-center gap-2"><span className="size-1.5 animate-pulse rounded-full bg-red-400" /> Live feed · scene 01</span><span>00:00:07 · 6 spans · 24 fps</span></div>
      <div className="relative z-10 mt-8 flex flex-col justify-between gap-5 lg:flex-row lg:items-end">
        <div><p className="text-[9px] font-bold uppercase tracking-[.18em] text-primary">Live system map</p><h2 className="mt-2 text-3xl font-black uppercase leading-none tracking-[-.04em] sm:text-5xl">Inference now.<br /><span className="text-white/30">Learning later.</span></h2><p className="mt-4 max-w-3xl text-xs leading-6 text-white/45">Race-day facts move through retrieval and a governed agent workflow in real time. Only human-approved edits may cross into the separate offline fine-tuning loop.</p></div>
        <fieldset className="flex w-fit rounded-full border border-white/10 bg-black/20 p-1"><legend className="sr-only">Highlight a system flow</legend><button type="button" onClick={() => setFocus('live')} aria-pressed={focus === 'live'} className={`rounded-full px-4 py-2 text-[10px] font-bold uppercase tracking-[.12em] transition ${focus === 'live' ? 'bg-primary text-primary-foreground' : 'text-white/35 hover:text-white'}`}>Follow live request</button><button type="button" onClick={() => setFocus('training')} aria-pressed={focus === 'training'} className={`rounded-full px-4 py-2 text-[10px] font-bold uppercase tracking-[.12em] transition ${focus === 'training' ? 'bg-amber-200 text-black' : 'text-white/35 hover:text-white'}`}>Inspect tuning loop</button></fieldset>
      </div>
      <div className="relative z-10 mt-8 flex items-center gap-1 overflow-hidden" aria-hidden="true">{Array.from({ length: 24 }).map((_, index) => <span key={index} className={`h-1 min-w-3 flex-1 rounded-full ${index < 17 ? 'bg-primary/35' : 'bg-white/8'}`} />)}</div>
    </section>

    <FlowLane label="Online inference path" status="RUNNING" tone="live" active={focus === 'live'} nodes={liveFlow} />

    <section className="grid gap-3 lg:grid-cols-[1fr_auto_1fr] lg:items-center">
      <div className="telemetry-film rounded-xl border border-emerald-300/15 bg-emerald-300/[.03] p-4"><div className="flex items-center justify-between gap-3"><span className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.14em] text-emerald-300"><Activity className="size-3.5 animate-pulse" /> Observability rail</span><EvidenceLink href={evidence.traceRecorder} compact /></div><div className="mt-3 grid grid-cols-4 gap-2"><FlowMetric value="6" label="spans" /><FlowMetric value="7 ms" label="fixture" /><FlowMetric value="0" label="errors" /><FlowMetric value="redacted" label="prompts" /></div></div>
      <div className="mx-auto flex flex-col items-center gap-1 text-center"><span className="approval-beam h-5 w-px bg-gradient-to-b from-emerald-300/60 to-amber-200/60" /><span className="rounded-full border border-white/10 bg-[#111713] px-4 py-2 text-[8px] font-bold uppercase tracking-[.14em] text-white/45">approved edits only ↓</span><span className="approval-beam h-5 w-px bg-gradient-to-b from-emerald-300/60 to-amber-200/60" /></div>
      <div className="rounded-xl border border-amber-200/15 bg-amber-200/[.03] p-4"><div className="flex items-center justify-between gap-3"><span className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.14em] text-amber-200"><GitBranch className="size-3.5" /> Learning feedback</span><EvidenceLink href={evidence.trainingData} compact /></div><p className="mt-3 text-[10px] leading-5 text-white/35">Rejected, synthetic, or unreviewed drafts never become training examples. Editor approval is the bridge between the two systems.</p></div>
    </section>

    <FlowLane label="Offline fine-tuning path" status="GATED" tone="training" active={focus === 'training'} nodes={trainingFlow} />

    <section className="grid gap-4 lg:grid-cols-[1fr_1fr]">
      <div className="rounded-2xl border border-amber-200/20 bg-amber-200/[.04] p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-[9px] font-bold uppercase tracking-[.16em] text-amber-200">Current stop point</p><h3 className="mt-2 text-xl font-semibold">Dataset gate blocks training</h3></div><span className="rounded-full bg-amber-200/10 px-3 py-1 font-mono text-[9px] text-amber-200">0 / 20</span></div><p className="mt-4 text-xs leading-6 text-white/40">No adapter, challenger benchmark, merge, or local deployment can occur until approved examples meet the minimum gate.</p><div className="mt-4"><EvidenceLink href={evidence.index + '#verification-snapshot'} label="Verify stop point" /></div></div>
      <div className="rounded-2xl border border-primary/20 bg-primary/[.04] p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-[9px] font-bold uppercase tracking-[.16em] text-primary">Release feedback loop</p><h3 className="mt-2 text-xl font-semibold">A challenger must earn the live lane</h3></div><FlaskConical className="size-5 text-primary" /></div><p className="mt-4 text-xs leading-6 text-white/40">QLoRA returns to production only after the same held-out evaluation proves it beats prompt + RAG on grounding, safety, style, latency, and cost.</p><div className="mt-4"><EvidenceLink href={evidence.modelCard} label="Open release criteria" /></div></div>
    </section>
  </div>;
}

function Overview() { return <div className="mt-4 grid gap-4 xl:grid-cols-[1fr_1fr_360px]">
  <Panel eyebrow="Release decision" title="Prompt + RAG remains selected" icon={<ShieldCheck />} evidenceHref={evidence.modelCard}><div className="mt-6 grid grid-cols-3 gap-px overflow-hidden rounded-xl border border-white/10 bg-white/10"><StatusCell label="Prompt only" value="Not benchmarked" status="neutral" href={evidence.index + '#claim-to-evidence-matrix'} /><StatusCell label="Prompt + RAG" value="Selected" status="pass" href={evidence.provider} /><StatusCell label="QLoRA + RAG" value="Not trained" status="warn" href={evidence.index + '#verification-snapshot'} /></div><p className="mt-5 text-xs leading-6 text-white/40">Fine-tuning ships only after it beats the simpler prompt-plus-RAG system on predeclared grounding, safety, style, latency, and cost thresholds.</p></Panel>
  <Panel eyebrow="Measured release suite" title="4 / 4 gates passed" icon={<FlaskConical />} evidenceHref={evidence.index + '#verification-snapshot'}><div className="mt-6 space-y-3">{evals.map((item) => <div key={item.name}><div className="mb-1.5 flex items-center justify-between gap-3 text-[10px]"><span className="text-white/45">{item.name}</span><span className="flex items-center gap-2"><EvidenceLink href={item.href} compact /><span className="font-mono text-emerald-300">PASS</span></span></div><div className="h-1.5 overflow-hidden rounded-full bg-white/8"><div className="h-full rounded-full bg-primary" style={{ width: `${item.inverse ? 100 : item.score}%` }} /></div></div>)}</div><p className="mt-5 font-mono text-[9px] text-white/25">ultramedia-release-v1 · 6 deterministic cases</p></Panel>
  <Panel eyebrow="Implementation state" title="Pipeline inventory" icon={<Layers3 />} evidenceHref={evidence.index}><div className="mt-5 space-y-2"><Inventory label="Data preparation" state="Implemented" href={evidence.trainingData} /><Inventory label="QLoRA training" state="Implemented" href={evidence.qlora} /><Inventory label="Adapter merge" state="Implemented" href={evidence.merge} /><Inventory label="Ollama packaging" state="Documented" href={evidence.ollama} /><Inventory label="Adapter artifact" state="Not produced" warn href={evidence.index + '#verification-snapshot'} /><Inventory label="Provider benchmark" state="Not run" warn href={evidence.index + '#evidence-boundaries'} /></div></Panel>
  <div className="xl:col-span-2"><Panel eyebrow="Fine-tuning lifecycle" title="Gates before a custom model can ship" icon={<GitBranch />} evidenceHref={evidence.index}><div className="mt-7 grid gap-2 md:grid-cols-5"><Lifecycle number="01" title="Curate" detail="Approved drafts only" state="current" href={evidence.trainingData} /><Lifecycle number="02" title="Train" detail="4-bit QLoRA" state="blocked" href={evidence.qlora} /><Lifecycle number="03" title="Evaluate" detail="Against RAG baseline" state="waiting" href={evidence.modelCard} /><Lifecycle number="04" title="Merge" detail="PEFT → model" state="waiting" href={evidence.merge} /><Lifecycle number="05" title="Serve" detail="GGUF + Ollama" state="waiting" href={evidence.ollama} /></div></Panel></div>
  <Panel eyebrow="Actual verification" title="Tests and traces" icon={<TerminalSquare />} evidenceHref={evidence.index + '#verification-snapshot'}><div className="mt-6 grid grid-cols-2 gap-2"><Metric value="6 / 6" label="Python tests passed" href={evidence.tests} /><Metric value="6" label="Eval cases executed" href={evidence.evals} /><Metric value="6" label="Trace spans recorded" href={evidence.workflow} /><Metric value="0" label="Sensitive inferences" href={`${repo}/blob/main/backend/src/ultramedia/evals.py#L40-L67`} /></div><div className="mt-5 flex w-full items-center justify-between rounded-xl border border-white/8 bg-white/[.02] p-3 text-left"><span><span className="block text-xs font-semibold">Local deterministic provider</span><span className="mt-1 block text-[9px] text-white/30">Zero token cost · reproducible fixture</span></span><EvidenceLink href={evidence.provider} compact /></div></Panel>
</div>; }

function FineTuning() { return <div className="mt-4"><section className="grid gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/10 lg:grid-cols-5">{methods.map((item) => <article key={item.number} className="bg-[#0d120f] p-5"><div className="flex items-start justify-between"><span className="text-primary [&>svg]:size-5">{item.icon}</span><span className="font-mono text-[9px] text-white/20">{item.number}</span></div><h2 className="mt-10 text-lg font-semibold">{item.title}</h2><p className="mt-3 min-h-24 text-xs leading-6 text-white/40">{item.body}</p><div className="mt-5 space-y-2 border-t border-white/8 pt-4">{item.facts.map((fact) => <p key={fact} className="flex items-center gap-2 text-[10px] text-white/45"><Check className="size-3 text-primary" /> {fact}</p>)}</div><div className="mt-4"><EvidenceLink href={item.href} /></div></article>)}</section>
  <section className="mt-4 grid gap-4 lg:grid-cols-[1fr_390px]"><Panel eyebrow="Training configuration" title="Qwen3-4B-Instruct-2507 + QLoRA" icon={<Server />} evidenceHref={evidence.qlora}><div className="mt-7 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="border-b border-white/10 text-[9px] uppercase tracking-[.14em] text-white/30"><tr><th className="pb-3">Layer</th><th className="pb-3">Choice</th><th className="pb-3">Why it is here</th><th className="pb-3 text-right">Evidence</th></tr></thead><tbody className="divide-y divide-white/6"><ConfigRow layer="Base model" value="Qwen3-4B-Instruct-2507" why="Apache-2.0, small enough for portfolio-scale local work" href={evidence.qwenLicense} /><ConfigRow layer="Quantization" value="4-bit NF4 + double quant" why="Reduces the memory needed to load frozen base weights" href={`${repo}/blob/main/backend/scripts/train_qlora.py#L21-L32`} /><ConfigRow layer="Adapters" value="r=16 · alpha=32 · dropout=.05" why="Trains a small, mergeable behavior layer" href={`${repo}/blob/main/backend/scripts/train_qlora.py#L38-L44`} /><ConfigRow layer="Optimization" value="2 epochs · LR 2e-4 · warmup 5%" why="Conservative supervised adaptation with step evaluation" href={`${repo}/blob/main/backend/scripts/train_qlora.py#L45-L60`} /><ConfigRow layer="Sequence" value="2,048 tokens" why="Fits evidence plus multi-channel story output" href={`${repo}/blob/main/backend/scripts/train_qlora.py#L45-L60`} /><ConfigRow layer="Batching" value="2 × accumulation 8 = effective 16" why="Balances memory limits and update stability" href={`${repo}/blob/main/backend/scripts/train_qlora.py#L45-L60`} /></tbody></table></div></Panel><Panel eyebrow="What tuning learns" title="Behavior, not facts" icon={<ShieldCheck />} evidenceHref={evidence.modelCard}><div className="mt-6 space-y-3"><LearnRow yes label="Editorial voice and headline discipline" href={evidence.trainingData} /><LearnRow yes label="Structured JSON response shape" href={evidence.trainingData} /><LearnRow yes label="Citation placement and abstention style" href={evidence.trainingData} /><LearnRow yes label="Human-handoff behavior" href={evidence.modelCard} /><LearnRow label="Current rankings, splits, weather, or cutoffs" href={evidence.retrieval} /><LearnRow label="Medical conclusions or athlete intent" href={evidence.modelCard} /></div><div className="mt-6 rounded-xl border border-primary/15 bg-primary/[.04] p-4 text-[10px] leading-5 text-white/45">Live and historical race facts stay in retrieval. This keeps the adapter stable while the evidence layer changes every race day. <span className="ml-1"><EvidenceLink href={evidence.retrieval} compact /></span></div></Panel></section>
</div>; }

function Evals() { return <div className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1fr)_390px]"><Panel eyebrow="Measured · local deterministic" title="ultramedia-release-v1" icon={<FlaskConical />} evidenceHref={evidence.index + '#verification-snapshot'}><div className="mt-7 space-y-3">{evals.map((item) => <div key={item.name} className="grid gap-4 rounded-xl border border-white/8 bg-white/[.02] p-4 sm:grid-cols-[1fr_110px_150px]"><div><p className="text-sm font-semibold">{item.name}</p><p className="mt-1 text-[10px] leading-5 text-white/35">{item.note}</p></div><div><p className="font-mono text-lg text-primary">{item.score}%</p><p className="text-[9px] text-white/25">Target {item.target}</p></div><div className="flex flex-wrap items-start gap-2"><Badge variant="outline" className="h-fit w-fit border-emerald-300/20 bg-emerald-300/5 text-emerald-300"><Check className="mr-1 size-3" /> PASS</Badge><EvidenceLink href={item.href} compact /></div></div>)}</div></Panel><div className="space-y-4"><Panel eyebrow="Result scope" title="What this proves" icon={<CheckCircle2 />} evidenceHref={evidence.evals}><ul className="mt-5 space-y-3 text-xs leading-5 text-white/45"><EvidenceListItem text="Retrieval finds the expected source in the top three." href={`${repo}/blob/main/backend/src/ultramedia/evals.py#L10-L23`} /><EvidenceListItem text="Generated fixture stories include citations." href={`${repo}/blob/main/backend/src/ultramedia/evals.py#L24-L56`} /><EvidenceListItem text="Publication always pauses for a human editor." href={`${repo}/blob/main/backend/tests/test_api.py#L14-L61`} /><EvidenceListItem text="The safety test produces zero unsupported sensitive claims." href={`${repo}/blob/main/backend/src/ultramedia/evals.py#L40-L67`} /></ul></Panel><Panel eyebrow="Result boundary" title="What this does not prove" icon={<X />} evidenceHref={evidence.index + '#evidence-boundaries'}><ul className="mt-5 space-y-3 text-xs leading-5 text-white/45"><EvidenceListItem text="No fine-tuned adapter quality has been measured." href={evidence.index + '#verification-snapshot'} /><EvidenceListItem text="Six cases are a smoke test, not a production benchmark." href={evidence.index + '#evidence-boundaries'} /><EvidenceListItem text="Cloud-model latency and cost were not tested." href={evidence.modelCard} /><EvidenceListItem text="Race-level fairness and long-tail coverage remain future suites." href={evidence.modelCard} /></ul></Panel><div className="rounded-2xl border border-emerald-300/20 bg-emerald-300/[.04] p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-emerald-300">Current release decision</p><p className="mt-3 text-4xl font-semibold">PASS</p><p className="mt-2 text-xs text-white/35">For the deterministic base + RAG demo only.</p></div><EvidenceLink href={evidence.index + '#verification-snapshot'} compact /></div></div></div></div>; }

function Traces() { const total = trace.reduce((sum, item) => sum + item.duration, 0); return <div className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1fr)_390px]"><Panel eyebrow="Measured workflow trace" title="Six agents · one governed draft" icon={<Workflow />} evidenceHref={evidence.workflow}><div className="mt-7 space-y-2">{trace.map((item, index) => <div key={item.stage} className="grid grid-cols-[42px_1fr_auto] items-center gap-3 rounded-xl border border-white/8 bg-white/[.02] p-4"><span className="grid size-8 place-items-center rounded-lg bg-primary/10 font-mono text-[10px] text-primary">0{index + 1}</span><div><p className="font-mono text-xs text-primary">{item.stage}</p><p className="mt-1 text-[10px] leading-5 text-white/40">{item.detail}</p><div className="mt-2 h-1 overflow-hidden rounded-full bg-white/8"><div className="h-full bg-primary" style={{ width: `${Math.max(30, item.duration / 2 * 100)}%` }} /></div></div><div className="text-right"><p className="font-mono text-xs">{item.duration} ms</p><p className="mt-1 text-[9px] text-emerald-300">PASSED</p><div className="mt-2"><EvidenceLink href={item.href} compact /></div></div></div>)}</div></Panel><div className="space-y-4"><Panel eyebrow="Trace summary" title={`${total} ms recorded`} icon={<Clock3 />} evidenceHref={evidence.index + '#verification-snapshot'}><div className="mt-6 grid grid-cols-2 gap-2"><Metric value="6" label="Spans" href={evidence.tests} /><Metric value="0" label="Errors" href={evidence.index + '#verification-snapshot'} /><Metric value="2 ms" label="Longest span" href={evidence.index + '#claim-to-evidence-matrix'} /><Metric value="100%" label="Completed" href={evidence.index + '#verification-snapshot'} /></div><p className="mt-5 text-[10px] leading-5 text-white/35">Durations come from the local deterministic fixture and should not be interpreted as LLM production latency. <span className="ml-1"><EvidenceLink href={evidence.index + '#evidence-boundaries'} compact /></span></p></Panel><Panel eyebrow="Privacy posture" title="Minimal trace payload" icon={<ShieldCheck />} evidenceHref={evidence.traceRecorder}><div className="mt-5 space-y-2"><Inventory label="Stage name" state="Stored" href={evidence.traceRecorder} /><Inventory label="Duration and status" state="Stored" href={evidence.traceRecorder} /><Inventory label="Operational detail" state="Stored" href={evidence.traceRecorder} /><Inventory label="Raw prompts" state="Excluded" href={evidence.traceRecorder} /><Inventory label="Full story body" state="Excluded" href={evidence.traceRecorder} /></div></Panel></div></div>; }

type NodeVisualKind = 'signal' | 'rag' | 'writer' | 'safety' | 'review' | 'approved' | 'gate' | 'qlora' | 'eval' | 'serve';
type FlowNodeData = { number: string; title: string; detail: string; metric: string; visual: NodeVisualKind; icon: React.ReactNode; state: 'active' | 'pass' | 'gated' | 'waiting'; href: string };
function FlowLane({ label, status, tone, active, nodes }: { label: string; status: string; tone: 'live' | 'training'; active: boolean; nodes: FlowNodeData[] }) { const live = tone === 'live'; return <section className={`flow-lane relative overflow-hidden rounded-2xl border p-5 transition duration-500 sm:p-6 ${live ? 'flow-lane-live border-emerald-300/20 bg-emerald-300/[.025]' : 'flow-lane-training border-amber-200/20 bg-amber-200/[.025]'} ${active ? 'scale-[1.005] opacity-100 shadow-[0_0_80px_rgba(196,255,74,.07)]' : 'opacity-45 hover:opacity-90'}`}><div className="relative z-10 mb-5 flex items-center justify-between gap-4"><div className="flex items-center gap-3"><span className={`relative flex size-3 ${live ? 'text-emerald-300' : 'text-amber-200'}`}><span className={`absolute inline-flex size-full animate-ping rounded-full opacity-40 ${live ? 'bg-emerald-300' : 'bg-amber-200'}`} /><span className={`relative inline-flex size-3 rounded-full ${live ? 'bg-emerald-300' : 'bg-amber-200'}`} /></span><h3 className="text-sm font-semibold">{label}</h3></div><span className={`rounded-full border px-3 py-1 font-mono text-[9px] ${live ? 'border-emerald-300/20 text-emerald-300' : 'border-amber-200/20 text-amber-200'}`}>{status}</span></div><div className="relative z-10 flex snap-x gap-2 overflow-x-auto pb-2">{nodes.map((node, index) => <div key={node.title} className="contents"><FlowNode node={node} tone={tone} />{index < nodes.length - 1 && <div className="flow-connector relative my-auto h-px w-8 shrink-0 overflow-visible bg-white/10"><span className={`flow-packet absolute -top-1 left-0 size-2 rounded-full ${live ? 'bg-emerald-300 shadow-[0_0_14px_#6ee7b7]' : 'bg-amber-200 shadow-[0_0_14px_#fde68a]'}`} style={{ animationDelay: `${index * .55}s` }} /><span className="absolute -right-1 -top-2.5 text-sm text-white/20">›</span></div>}</div>)}</div></section>; }
function FlowNode({ node, tone }: { node: FlowNodeData; tone: 'live' | 'training' }) { const live = tone === 'live'; const gated = node.state === 'gated'; const waiting = node.state === 'waiting'; return <article style={{ animationDelay: `${(Number(node.number) - 1) * .45}s` }} className={`flow-node group min-w-[185px] flex-1 snap-start rounded-xl border p-4 transition hover:-translate-y-0.5 ${gated ? 'flow-node-gated border-amber-200/30 bg-amber-200/[.05]' : waiting ? 'flow-node-waiting border-white/8 bg-black/10' : live ? 'flow-node-live border-emerald-300/15 bg-[#101713]' : 'border-amber-200/15 bg-[#17150f]'}`}><div className="flex items-start justify-between"><span className="font-mono text-[8px] uppercase tracking-[.14em] text-white/20">scene</span><span className="font-mono text-[8px] text-white/20">{node.number}</span></div><NodeVisual kind={node.visual} icon={node.icon} tone={tone} /><p className="mt-4 text-sm font-semibold">{node.title}</p><p className="mt-1 min-h-8 text-[9px] leading-4 text-white/35">{node.detail}</p><div className="mt-4 flex items-center justify-between gap-2"><span className={`font-mono text-[8px] ${gated ? 'text-amber-200' : waiting ? 'text-white/25' : 'text-emerald-300'}`}>{node.metric}</span><EvidenceLink href={node.href} compact /></div></article>; }
function NodeVisual({ kind, icon, tone }: { kind: NodeVisualKind; icon: React.ReactNode; tone: 'live' | 'training' }) { const theme = tone === 'live' ? 'node-visual-live' : 'node-visual-training'; return <div className={`node-visual ${theme} node-visual-${kind}`} aria-hidden="true"><div className="node-visual-grid" /><span className="node-visual-icon">{icon}</span>{kind === 'signal' && <><span className="visual-ring visual-ring-one" /><span className="visual-ring visual-ring-two" /><span className="visual-signal-dot" /></>}{kind === 'rag' && <><span className="visual-data-line visual-data-line-one" /><span className="visual-data-line visual-data-line-two" /><span className="visual-data-line visual-data-line-three" /><span className="visual-data-chip visual-data-chip-one" /><span className="visual-data-chip visual-data-chip-two" /><span className="visual-data-chip visual-data-chip-three" /></>}{kind === 'writer' && <div className="visual-page"><span className="visual-type-line visual-type-line-one" /><span className="visual-type-line visual-type-line-two" /><span className="visual-type-line visual-type-line-three" /></div>}{kind === 'safety' && <><span className="visual-safety-frame" /><span className="visual-safety-scan" /><span className="visual-safe-check">✓</span></>}{kind === 'review' && <><span className="visual-review-card visual-review-card-back" /><span className="visual-review-card visual-review-card-front" /><span className="visual-approval-stamp">APPROVE</span></>}{kind === 'approved' && <><span className="visual-edit visual-edit-one" /><span className="visual-edit visual-edit-two" /><span className="visual-edit visual-edit-three" /><span className="visual-approved-check">✓</span></>}{kind === 'gate' && <><span className="visual-gate visual-gate-left" /><span className="visual-gate visual-gate-right" /><span className="visual-gate-lock">0 / 20</span></>}{kind === 'qlora' && <><span className="visual-orbit visual-orbit-one"><i /></span><span className="visual-orbit visual-orbit-two"><i /></span><span className="visual-rank">r16</span></>}{kind === 'eval' && <><span className="visual-eval-axis" /><span className="visual-eval-bar visual-eval-base" /><span className="visual-eval-bar visual-eval-challenger" /><span className="visual-eval-label">A/B</span></>}{kind === 'serve' && <><span className="visual-model visual-model-base">BASE</span><span className="visual-model visual-model-adapter">LORA</span><span className="visual-merge-arrow">→</span><span className="visual-serve-slot" /></>}</div>; }
function FlowMetric({ value, label }: { value: string; label: string }) { return <div className="rounded-lg border border-white/6 bg-black/10 p-2 text-center"><p className="font-mono text-xs text-white/70">{value}</p><p className="mt-1 text-[8px] uppercase tracking-[.1em] text-white/25">{label}</p></div>; }
function NavTab({ active, onClick, icon, label }: { active: boolean; onClick: () => void; icon: React.ReactNode; label: string }) { return <button onClick={onClick} className={`flex shrink-0 items-center gap-2 rounded-lg px-4 py-2.5 text-xs font-semibold transition [&>svg]:size-3.5 ${active ? 'bg-primary text-primary-foreground' : 'text-white/40 hover:bg-white/5 hover:text-white'}`}>{icon}{label}</button>; }
function EvidenceLink({ href, label = 'Evidence', compact = false }: { href: string; label?: string; compact?: boolean }) { return <a href={href} target="_blank" rel="noreferrer" aria-label={`${label} (opens in a new tab)`} className={`inline-flex shrink-0 items-center gap-1 rounded-full border border-primary/20 bg-primary/[.05] font-semibold text-primary transition hover:border-primary/40 hover:bg-primary/10 ${compact ? 'px-2 py-1 text-[8px]' : 'px-3 py-1.5 text-[9px]'}`}>{compact ? 'EVIDENCE' : label}<ArrowUpRight className="size-2.5" /></a>; }
function EvidenceListItem({ text, href }: { text: string; href: string }) { return <li className="flex items-start justify-between gap-3"><span>• {text}</span><EvidenceLink href={href} compact /></li>; }
function Panel({ eyebrow, title, icon, children, evidenceHref }: { eyebrow: string; title: string; icon: React.ReactNode; children: React.ReactNode; evidenceHref?: string }) { return <section className="rounded-2xl border border-white/10 bg-[#0d120f] p-5 sm:p-6"><div className="flex items-start justify-between gap-5"><div><p className="text-[9px] font-bold uppercase tracking-[.18em] text-primary">{eyebrow}</p><h2 className="mt-2 text-xl font-semibold">{title}</h2>{evidenceHref && <div className="mt-3"><EvidenceLink href={evidenceHref} /></div>}</div><span className="text-primary [&>svg]:size-5">{icon}</span></div>{children}</section>; }
function StatusCell({ label, value, status, href }: { label: string; value: string; status: 'pass' | 'warn' | 'neutral'; href: string }) { return <div className="bg-[#101612] p-4"><span className={`mb-5 block size-2 rounded-full ${status === 'pass' ? 'bg-emerald-300' : status === 'warn' ? 'bg-amber-300' : 'bg-white/20'}`} /><p className="text-[9px] text-white/30">{label}</p><p className="mt-1 text-xs font-semibold">{value}</p><div className="mt-3"><EvidenceLink href={href} compact /></div></div>; }
function Inventory({ label, state, warn = false, href }: { label: string; state: string; warn?: boolean; href: string }) { return <div className="flex items-center justify-between gap-3 rounded-lg border border-white/6 px-3 py-2.5"><span className="text-[10px] text-white/45">{label}</span><span className="flex items-center gap-2"><span className={`font-mono text-[9px] ${warn ? 'text-amber-200' : 'text-emerald-300'}`}>{state}</span><EvidenceLink href={href} compact /></span></div>; }
function Lifecycle({ number, title, detail, state, href }: { number: string; title: string; detail: string; state: 'current' | 'blocked' | 'waiting'; href: string }) { return <div className={`rounded-xl border p-4 ${state === 'current' ? 'border-primary/30 bg-primary/[.06]' : state === 'blocked' ? 'border-amber-300/20 bg-amber-300/[.04]' : 'border-white/8 bg-white/[.02]'}`}><div className="flex justify-between font-mono text-[9px]"><span className={state === 'current' ? 'text-primary' : state === 'blocked' ? 'text-amber-200' : 'text-white/25'}>{number}</span><span className="text-white/25">{state}</span></div><p className="mt-7 text-sm font-semibold">{title}</p><p className="mt-1 text-[9px] text-white/35">{detail}</p><div className="mt-3"><EvidenceLink href={href} compact /></div></div>; }
function Metric({ value, label, href }: { value: string; label: string; href: string }) { return <div className="rounded-xl border border-white/8 bg-white/[.02] p-3"><p className="font-mono text-lg text-primary">{value}</p><p className="mt-1 text-[9px] text-white/30">{label}</p><div className="mt-2"><EvidenceLink href={href} compact /></div></div>; }
function ConfigRow({ layer, value, why, href }: { layer: string; value: string; why: string; href: string }) { return <tr><td className="py-4 font-semibold">{layer}</td><td className="py-4 font-mono text-primary">{value}</td><td className="py-4 text-white/40">{why}</td><td className="py-4 text-right"><EvidenceLink href={href} compact /></td></tr>; }
function LearnRow({ yes = false, label, href }: { yes?: boolean; label: string; href: string }) { return <div className="flex items-center gap-3 rounded-lg border border-white/6 p-3"><span className={`grid size-5 shrink-0 place-items-center rounded-full ${yes ? 'bg-emerald-300/10 text-emerald-300' : 'bg-white/5 text-white/25'}`}>{yes ? <Check className="size-3" /> : <X className="size-3" />}</span><span className="min-w-0 flex-1 text-[10px] text-white/50">{label}</span><EvidenceLink href={href} compact /></div>; }
