'use client';

import { useState } from 'react';
import Link from 'next/link';
import { Activity, ArrowLeft, ArrowUpRight, Ban, Boxes, Check, CheckCircle2, CircleDot, Clock3, Code2, Database, Download, FlaskConical, GitBranch, Layers3, Radio, Server, ShieldCheck, SlidersHorizontal, TerminalSquare, Workflow, X } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { buttonVariants } from '@/components/ui/button';

type View = 'overview' | 'finetuning' | 'evals' | 'traces';

const evals = [
  { name: 'Retrieval recall @3', score: 100, target: '≥ 75%', note: '4/4 expected evidence records retrieved' },
  { name: 'Citation validity', score: 100, target: '= 100%', note: 'Every generated draft carried citations' },
  { name: 'Human review gate', score: 100, target: '= 100%', note: 'Every draft stopped at pending review' },
  { name: 'Unsupported sensitive inference', score: 0, target: '= 0%', note: 'No invented injury, collapse, or dehydration claim', inverse: true },
];

const trace = [
  { stage: 'moment_detector', duration: 1, detail: 'Validated race signal and athlete reference' },
  { stage: 'evidence_retriever', duration: 2, detail: 'Hybrid retrieval over timing and course context' },
  { stage: 'story_writer', duration: 1, detail: 'Generated structured draft with local-deterministic' },
  { stage: 'fact_verifier', duration: 1, detail: 'Checked citations and claim support' },
  { stage: 'safety_editor', duration: 1, detail: 'Blocked unsupported health and intent inferences' },
  { stage: 'human_review_queue', duration: 1, detail: 'Stored draft as pending; no automatic publication' },
];

const methods = [
  { icon: <Database />, number: '01', title: 'Approval-only dataset', body: 'Only editor-approved story drafts can enter training. Each example retains the evidence IDs used to support its claims.', facts: ['Minimum 20 examples', '90 / 10 train-validation split', 'Deterministic seed · 42'] },
  { icon: <Boxes />, number: '02', title: '4-bit QLoRA', body: 'The 4B base model is loaded in NF4 with double quantization. Low-rank weights are trained while the quantized base remains frozen.', facts: ['NF4 · double quantization', 'bfloat16 compute', 'Lower GPU memory'] },
  { icon: <SlidersHorizontal />, number: '03', title: 'LoRA adapters', body: 'Rank-16 adapters target attention and MLP projections so the model learns newsroom structure without relearning race facts.', facts: ['r 16 · alpha 32', 'Dropout 0.05', 'q/k/v/o + gate/up/down'] },
  { icon: <Code2 />, number: '04', title: 'Supervised tuning', body: 'TRL’s SFT trainer teaches headline discipline, citation placement, abstention, and channel-ready JSON formatting.', facts: ['2 epochs', 'LR 2e-4 · warmup 5%', 'Effective batch size 16'] },
  { icon: <GitBranch />, number: '05', title: 'Merge and package', body: 'PEFT merges a passing adapter into Qwen3. The merged model can then be converted to GGUF and served locally through Ollama.', facts: ['Safe tensors', 'GGUF conversion path', 'Local-first inference'] },
];

export default function ObservabilityPage() {
  const [view, setView] = useState<View>('overview');
  return (
    <main className="min-h-screen bg-[#080b09] text-foreground">
      <header className="sticky top-0 z-50 border-b border-white/10 bg-[#080b09]/95 backdrop-blur-xl">
        <div className="mx-auto flex h-16 max-w-[1600px] items-center justify-between px-4 sm:px-6">
          <div className="flex items-center gap-3"><Link href="/" className={buttonVariants({ variant: 'ghost', size: 'icon-sm', className: 'rounded-full' })} aria-label="Back to UltraMedia home"><ArrowLeft className="size-4" /></Link><span className="grid size-8 place-items-center rounded-full bg-primary text-primary-foreground"><Activity className="size-4" /></span><div><p className="text-xs font-black">ULTRAMEDIA <span className="text-white/40">MODEL OPS</span></p><p className="text-[9px] uppercase tracking-[.15em] text-white/30">Evidence console</p></div></div>
          <div className="hidden items-center gap-5 text-xs font-semibold text-white/40 md:flex"><Link href="/races" className="hover:text-white">Race atlas</Link><Link href="/studio" className="hover:text-white">Newsroom</Link><span className="text-primary">Observability</span></div>
          <Badge variant="outline" className="border-emerald-300/20 bg-emerald-300/5 text-emerald-300"><span className="mr-2 size-1.5 rounded-full bg-emerald-300" /> Base + RAG · PASS</Badge>
        </div>
      </header>

      <div className="mx-auto max-w-[1600px] px-4 py-5 sm:px-6">
        <section className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_340px]">
          <div className="relative overflow-hidden rounded-2xl border border-white/10 bg-[#0d120f] p-6 sm:p-8">
            <div className="absolute inset-0 bg-[radial-gradient(circle_at_85%_0%,rgba(196,255,74,.12),transparent_35%)]" />
            <div className="relative flex flex-col justify-between gap-10 lg:flex-row lg:items-end"><div><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.2em] text-primary"><Radio className="size-3" /> Model release observability</div><h1 className="mt-4 text-4xl font-black uppercase leading-[.9] tracking-[-.055em] sm:text-6xl">What was built.<br /><span className="text-white/35">What actually ran.</span></h1><p className="mt-5 max-w-2xl text-sm leading-7 text-white/45">A truthful operational view of UltraMedia’s fine-tuning path, measured evaluation results, model decision, and agent execution—not a simulated training report.</p></div><div className="flex shrink-0 gap-2"><a href="/data/model-observability.json" download className={buttonVariants({ variant: 'outline', className: 'rounded-full border-white/15' })}><Download className="size-4" /> Export snapshot</a><Link href="/studio" className={buttonVariants({ className: 'rounded-full font-bold' })}>Open newsroom <ArrowUpRight className="size-4" /></Link></div></div>
          </div>
          <div className="rounded-2xl border border-amber-300/20 bg-amber-300/[.04] p-6"><div className="flex items-center justify-between"><div className="flex items-center gap-2 text-amber-200"><Ban className="size-4" /><p className="text-[10px] font-bold uppercase tracking-[.16em]">Training gate</p></div><Badge variant="outline" className="border-amber-300/20 text-amber-200">BLOCKED BY DESIGN</Badge></div><p className="mt-7 font-mono text-5xl font-semibold text-amber-200">0<span className="text-xl text-white/25"> / 20</span></p><p className="mt-2 text-xs text-white/40">Human-approved examples available</p><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-white/8"><div className="h-full w-0 bg-amber-200" /></div><p className="mt-4 text-[10px] leading-5 text-white/35">QLoRA training was not run and no adapter result is claimed. The guard prevents tuning on unreviewed synthetic drafts.</p></div>
        </section>

        <nav className="mt-4 flex gap-1 overflow-x-auto rounded-xl border border-white/10 bg-[#0d120f] p-1" aria-label="Observability views">
          <NavTab active={view === 'overview'} onClick={() => setView('overview')} icon={<CircleDot />} label="Overview" />
          <NavTab active={view === 'finetuning'} onClick={() => setView('finetuning')} icon={<SlidersHorizontal />} label="Fine-tuning method" />
          <NavTab active={view === 'evals'} onClick={() => setView('evals')} icon={<FlaskConical />} label="Measured evals" />
          <NavTab active={view === 'traces'} onClick={() => setView('traces')} icon={<Workflow />} label="Agent traces" />
          <div className="ml-auto hidden items-center gap-2 px-3 font-mono text-[9px] text-white/25 md:flex"><Clock3 className="size-3" /> Snapshot · Sep 6, 2026</div>
        </nav>

        {view === 'overview' && <Overview />}
        {view === 'finetuning' && <FineTuning />}
        {view === 'evals' && <Evals />}
        {view === 'traces' && <Traces />}

        <footer className="mt-5 flex flex-col justify-between gap-4 border-t border-white/10 py-7 text-xs text-white/30 sm:flex-row"><p>UltraMedia Model Ops · measured results are labeled separately from planned experiments</p><div className="flex gap-5"><a href="https://github.com/sivalinb/ultramedia-studio/blob/main/docs/MODEL_CARD.md" target="_blank" rel="noreferrer" className="hover:text-primary">Model card</a><a href="https://github.com/sivalinb/ultramedia-studio/tree/main/backend/scripts" target="_blank" rel="noreferrer" className="hover:text-primary">Training code</a></div></footer>
      </div>
    </main>
  );
}

function Overview() { return <div className="mt-4 grid gap-4 xl:grid-cols-[1fr_1fr_360px]">
  <Panel eyebrow="Release decision" title="Prompt + RAG remains selected" icon={<ShieldCheck />}><div className="mt-6 grid grid-cols-3 gap-px overflow-hidden rounded-xl border border-white/10 bg-white/10"><StatusCell label="Prompt only" value="Not benchmarked" status="neutral" /><StatusCell label="Prompt + RAG" value="Selected" status="pass" /><StatusCell label="QLoRA + RAG" value="Not trained" status="warn" /></div><p className="mt-5 text-xs leading-6 text-white/40">Fine-tuning ships only after it beats the simpler prompt-plus-RAG system on predeclared grounding, safety, style, latency, and cost thresholds.</p></Panel>
  <Panel eyebrow="Measured release suite" title="4 / 4 gates passed" icon={<FlaskConical />}><div className="mt-6 space-y-3">{evals.map((item) => <div key={item.name}><div className="mb-1.5 flex justify-between text-[10px]"><span className="text-white/45">{item.name}</span><span className="font-mono text-emerald-300">PASS</span></div><div className="h-1.5 overflow-hidden rounded-full bg-white/8"><div className="h-full rounded-full bg-primary" style={{ width: `${item.inverse ? 100 : item.score}%` }} /></div></div>)}</div><p className="mt-5 font-mono text-[9px] text-white/25">ultramedia-release-v1 · 6 deterministic cases</p></Panel>
  <Panel eyebrow="Implementation state" title="Pipeline inventory" icon={<Layers3 />}><div className="mt-5 space-y-2"><Inventory label="Data preparation" state="Implemented" /><Inventory label="QLoRA training" state="Implemented" /><Inventory label="Adapter merge" state="Implemented" /><Inventory label="Ollama packaging" state="Documented" /><Inventory label="Adapter artifact" state="Not produced" warn /><Inventory label="Provider benchmark" state="Not run" warn /></div></Panel>
  <div className="xl:col-span-2"><Panel eyebrow="Fine-tuning lifecycle" title="Gates before a custom model can ship" icon={<GitBranch />}><div className="mt-7 grid gap-2 md:grid-cols-5"><Lifecycle number="01" title="Curate" detail="Approved drafts only" state="current" /><Lifecycle number="02" title="Train" detail="4-bit QLoRA" state="blocked" /><Lifecycle number="03" title="Evaluate" detail="Against RAG baseline" state="waiting" /><Lifecycle number="04" title="Merge" detail="PEFT → model" state="waiting" /><Lifecycle number="05" title="Serve" detail="GGUF + Ollama" state="waiting" /></div></Panel></div>
  <Panel eyebrow="Actual verification" title="Tests and traces" icon={<TerminalSquare />}><div className="mt-6 grid grid-cols-2 gap-2"><Metric value="6 / 6" label="Python tests passed" /><Metric value="6" label="Eval cases executed" /><Metric value="6" label="Trace spans recorded" /><Metric value="0" label="Sensitive inferences" /></div><button onClick={() => {}} className="mt-5 flex w-full items-center justify-between rounded-xl border border-white/8 bg-white/[.02] p-3 text-left"><span><span className="block text-xs font-semibold">Local deterministic provider</span><span className="mt-1 block text-[9px] text-white/30">Zero token cost · reproducible fixture</span></span><CheckCircle2 className="size-4 text-emerald-300" /></button></Panel>
</div>; }

function FineTuning() { return <div className="mt-4"><section className="grid gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/10 lg:grid-cols-5">{methods.map((item) => <article key={item.number} className="bg-[#0d120f] p-5"><div className="flex items-start justify-between"><span className="text-primary [&>svg]:size-5">{item.icon}</span><span className="font-mono text-[9px] text-white/20">{item.number}</span></div><h2 className="mt-10 text-lg font-semibold">{item.title}</h2><p className="mt-3 min-h-24 text-xs leading-6 text-white/40">{item.body}</p><div className="mt-5 space-y-2 border-t border-white/8 pt-4">{item.facts.map((fact) => <p key={fact} className="flex items-center gap-2 text-[10px] text-white/45"><Check className="size-3 text-primary" /> {fact}</p>)}</div></article>)}</section>
  <section className="mt-4 grid gap-4 lg:grid-cols-[1fr_390px]"><Panel eyebrow="Training configuration" title="Qwen3-4B-Instruct-2507 + QLoRA" icon={<Server />}><div className="mt-7 overflow-x-auto"><table className="w-full min-w-[680px] text-left text-xs"><thead className="border-b border-white/10 text-[9px] uppercase tracking-[.14em] text-white/30"><tr><th className="pb-3">Layer</th><th className="pb-3">Choice</th><th className="pb-3">Why it is here</th></tr></thead><tbody className="divide-y divide-white/6"><ConfigRow layer="Base model" value="Qwen3-4B-Instruct-2507" why="Apache-2.0, small enough for portfolio-scale local work" /><ConfigRow layer="Quantization" value="4-bit NF4 + double quant" why="Reduces the memory needed to load frozen base weights" /><ConfigRow layer="Adapters" value="r=16 · alpha=32 · dropout=.05" why="Trains a small, mergeable behavior layer" /><ConfigRow layer="Optimization" value="2 epochs · LR 2e-4 · warmup 5%" why="Conservative supervised adaptation with step evaluation" /><ConfigRow layer="Sequence" value="2,048 tokens" why="Fits evidence plus multi-channel story output" /><ConfigRow layer="Batching" value="2 × accumulation 8 = effective 16" why="Balances memory limits and update stability" /></tbody></table></div></Panel><Panel eyebrow="What tuning learns" title="Behavior, not facts" icon={<ShieldCheck />}><div className="mt-6 space-y-3"><LearnRow yes label="Editorial voice and headline discipline" /><LearnRow yes label="Structured JSON response shape" /><LearnRow yes label="Citation placement and abstention style" /><LearnRow yes label="Human-handoff behavior" /><LearnRow label="Current rankings, splits, weather, or cutoffs" /><LearnRow label="Medical conclusions or athlete intent" /></div><div className="mt-6 rounded-xl border border-primary/15 bg-primary/[.04] p-4 text-[10px] leading-5 text-white/45">Live and historical race facts stay in retrieval. This keeps the adapter stable while the evidence layer changes every race day.</div></Panel></section>
</div>; }

function Evals() { return <div className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1fr)_390px]"><Panel eyebrow="Measured · local deterministic" title="ultramedia-release-v1" icon={<FlaskConical />}><div className="mt-7 space-y-3">{evals.map((item) => <div key={item.name} className="grid gap-4 rounded-xl border border-white/8 bg-white/[.02] p-4 sm:grid-cols-[1fr_110px_90px]"><div><p className="text-sm font-semibold">{item.name}</p><p className="mt-1 text-[10px] leading-5 text-white/35">{item.note}</p></div><div><p className="font-mono text-lg text-primary">{item.score}%</p><p className="text-[9px] text-white/25">Target {item.target}</p></div><Badge variant="outline" className="h-fit w-fit border-emerald-300/20 bg-emerald-300/5 text-emerald-300"><Check className="mr-1 size-3" /> PASS</Badge></div>)}</div></Panel><div className="space-y-4"><Panel eyebrow="Result scope" title="What this proves" icon={<CheckCircle2 />}><ul className="mt-5 space-y-3 text-xs leading-5 text-white/45"><li>• Retrieval finds the expected source in the top three.</li><li>• Generated fixture stories include citations.</li><li>• Publication always pauses for a human editor.</li><li>• The safety test produces zero unsupported sensitive claims.</li></ul></Panel><Panel eyebrow="Result boundary" title="What this does not prove" icon={<X />}><ul className="mt-5 space-y-3 text-xs leading-5 text-white/45"><li>• No fine-tuned adapter quality has been measured.</li><li>• Six cases are a smoke test, not a production benchmark.</li><li>• Cloud-model latency and cost were not tested.</li><li>• Race-level fairness and long-tail coverage remain future suites.</li></ul></Panel><div className="rounded-2xl border border-emerald-300/20 bg-emerald-300/[.04] p-6"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-emerald-300">Current release decision</p><p className="mt-3 text-4xl font-semibold">PASS</p><p className="mt-2 text-xs text-white/35">For the deterministic base + RAG demo only.</p></div></div></div>; }

function Traces() { const total = trace.reduce((sum, item) => sum + item.duration, 0); return <div className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1fr)_390px]"><Panel eyebrow="Measured workflow trace" title="Six agents · one governed draft" icon={<Workflow />}><div className="mt-7 space-y-2">{trace.map((item, index) => <div key={item.stage} className="grid grid-cols-[42px_1fr_auto] items-center gap-3 rounded-xl border border-white/8 bg-white/[.02] p-4"><span className="grid size-8 place-items-center rounded-lg bg-primary/10 font-mono text-[10px] text-primary">0{index + 1}</span><div><p className="font-mono text-xs text-primary">{item.stage}</p><p className="mt-1 text-[10px] leading-5 text-white/40">{item.detail}</p><div className="mt-2 h-1 overflow-hidden rounded-full bg-white/8"><div className="h-full bg-primary" style={{ width: `${Math.max(30, item.duration / 2 * 100)}%` }} /></div></div><div className="text-right"><p className="font-mono text-xs">{item.duration} ms</p><p className="mt-1 text-[9px] text-emerald-300">PASSED</p></div></div>)}</div></Panel><div className="space-y-4"><Panel eyebrow="Trace summary" title={`${total} ms recorded`} icon={<Clock3 />}><div className="mt-6 grid grid-cols-2 gap-2"><Metric value="6" label="Spans" /><Metric value="0" label="Errors" /><Metric value="2 ms" label="Longest span" /><Metric value="100%" label="Completed" /></div><p className="mt-5 text-[10px] leading-5 text-white/35">Durations come from the local deterministic fixture and should not be interpreted as LLM production latency.</p></Panel><Panel eyebrow="Privacy posture" title="Minimal trace payload" icon={<ShieldCheck />}><div className="mt-5 space-y-2"><Inventory label="Stage name" state="Stored" /><Inventory label="Duration and status" state="Stored" /><Inventory label="Operational detail" state="Stored" /><Inventory label="Raw prompts" state="Excluded" /><Inventory label="Full story body" state="Excluded" /></div></Panel></div></div>; }

function NavTab({ active, onClick, icon, label }: { active: boolean; onClick: () => void; icon: React.ReactNode; label: string }) { return <button onClick={onClick} className={`flex shrink-0 items-center gap-2 rounded-lg px-4 py-2.5 text-xs font-semibold transition [&>svg]:size-3.5 ${active ? 'bg-primary text-primary-foreground' : 'text-white/40 hover:bg-white/5 hover:text-white'}`}>{icon}{label}</button>; }
function Panel({ eyebrow, title, icon, children }: { eyebrow: string; title: string; icon: React.ReactNode; children: React.ReactNode }) { return <section className="rounded-2xl border border-white/10 bg-[#0d120f] p-5 sm:p-6"><div className="flex items-start justify-between gap-5"><div><p className="text-[9px] font-bold uppercase tracking-[.18em] text-primary">{eyebrow}</p><h2 className="mt-2 text-xl font-semibold">{title}</h2></div><span className="text-primary [&>svg]:size-5">{icon}</span></div>{children}</section>; }
function StatusCell({ label, value, status }: { label: string; value: string; status: 'pass' | 'warn' | 'neutral' }) { return <div className="bg-[#101612] p-4"><span className={`mb-5 block size-2 rounded-full ${status === 'pass' ? 'bg-emerald-300' : status === 'warn' ? 'bg-amber-300' : 'bg-white/20'}`} /><p className="text-[9px] text-white/30">{label}</p><p className="mt-1 text-xs font-semibold">{value}</p></div>; }
function Inventory({ label, state, warn = false }: { label: string; state: string; warn?: boolean }) { return <div className="flex items-center justify-between gap-3 rounded-lg border border-white/6 px-3 py-2.5"><span className="text-[10px] text-white/45">{label}</span><span className={`font-mono text-[9px] ${warn ? 'text-amber-200' : 'text-emerald-300'}`}>{state}</span></div>; }
function Lifecycle({ number, title, detail, state }: { number: string; title: string; detail: string; state: 'current' | 'blocked' | 'waiting' }) { return <div className={`rounded-xl border p-4 ${state === 'current' ? 'border-primary/30 bg-primary/[.06]' : state === 'blocked' ? 'border-amber-300/20 bg-amber-300/[.04]' : 'border-white/8 bg-white/[.02]'}`}><div className="flex justify-between font-mono text-[9px]"><span className={state === 'current' ? 'text-primary' : state === 'blocked' ? 'text-amber-200' : 'text-white/25'}>{number}</span><span className="text-white/25">{state}</span></div><p className="mt-7 text-sm font-semibold">{title}</p><p className="mt-1 text-[9px] text-white/35">{detail}</p></div>; }
function Metric({ value, label }: { value: string; label: string }) { return <div className="rounded-xl border border-white/8 bg-white/[.02] p-3"><p className="font-mono text-lg text-primary">{value}</p><p className="mt-1 text-[9px] text-white/30">{label}</p></div>; }
function ConfigRow({ layer, value, why }: { layer: string; value: string; why: string }) { return <tr><td className="py-4 font-semibold">{layer}</td><td className="py-4 font-mono text-primary">{value}</td><td className="py-4 text-white/40">{why}</td></tr>; }
function LearnRow({ yes = false, label }: { yes?: boolean; label: string }) { return <div className="flex items-center gap-3 rounded-lg border border-white/6 p-3"><span className={`grid size-5 place-items-center rounded-full ${yes ? 'bg-emerald-300/10 text-emerald-300' : 'bg-white/5 text-white/25'}`}>{yes ? <Check className="size-3" /> : <X className="size-3" />}</span><span className="text-[10px] text-white/50">{label}</span></div>; }
