import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '../..');
const { chromium } = await import('playwright');
const run = path.resolve(process.env.E2E_OUTPUT_DIR || path.join(root, 'week5/runs', 'e2e-' + new Date().toISOString().replaceAll(':', '-')));
await fs.mkdir(run, {recursive:true});
const reviewerKey = process.env.E2E_REVIEWER_KEY || (process.env.E2E_REVIEWER_KEY_FILE ? (await fs.readFile(process.env.E2E_REVIEWER_KEY_FILE, 'utf8')).trim() : '');
if (!reviewerKey) throw new Error('Set E2E_REVIEWER_KEY or E2E_REVIEWER_KEY_FILE for an isolated synthetic QA API.');
const expectedProvider = process.env.E2E_EXPECTED_PROVIDER || 'llamacpp:qwen3:4b-instruct';
const site = process.env.E2E_SITE_URL || 'http://localhost:3000';
const report = { started_at:new Date().toISOString(), scope:'Synthetic engineering QA with an actual local Qwen model; simulated review actions are not human editorial approval', steps:[], page_errors:[], passed:false };
const browser = await chromium.launch({headless:true});
const context = await browser.newContext({viewport:{width:1440,height:1000}, recordVideo:{dir:run,size:{width:1280,height:900}}});
const page = await context.newPage();
page.on('pageerror', e => report.page_errors.push(e.message));
const pass = (name, details={}) => {report.steps.push({name,passed:true,...details}); console.log(name);};
const api = process.env.E2E_API_URL || 'http://127.0.0.1:8000';
async function reviewClick(name, status) {
  const reply = page.waitForResponse(r => r.url().endsWith('/review') && r.request().method()==='POST');
  await page.getByRole('button',{name,exact:true}).click();
  const response = await reply;
  assert.equal(response.status(),status,await response.text());
  return response.json();
}
try {
  const response = await page.goto(`${site}/studio`,{waitUntil:'networkidle'});
  assert.equal(response.status(),200);
  assert.equal(await page.getByRole('button',{name:'Generate draft',exact:true}).isEnabled(),true);
  assert.equal(await page.getByRole('button',{name:'Save and approve',exact:true}).isDisabled(),true);
  pass('UI connected to API; review disabled before generation');
  const started = Date.now();
  const generated = page.waitForResponse(r=>r.url().endsWith('/stories/generate') && r.request().method()==='POST',{timeout:150000});
  await page.getByRole('button',{name:'Generate draft',exact:true}).click();
  const generatedResponse = await generated;
  assert.equal(generatedResponse.status(),201,await generatedResponse.text());
  const story = await generatedResponse.json();
  assert.equal(story.provider,expectedProvider);
  assert.equal(story.status,'pending_review');
  assert.equal(story.quality_checks.automatic_checks_passed,true);
  await page.getByRole('status').filter({hasText:'Draft saved'}).waitFor();
  await fs.writeFile(path.join(run,'generated-story.json'),JSON.stringify(story,null,2));
  pass('Browser → API → retrieval → local model → fact checks → persisted pending draft',{duration_ms:Date.now()-started,story_id:story.id});
  const trace = await (await context.request.get(`${api}/api/v1/traces/${story.trace_id}`)).json();
  assert.deepEqual(trace.spans.map(s=>s.stage),['moment_detector','evidence_retriever','story_writer','fact_verifier','safety_editor','human_review_queue']);
  assert.ok(trace.spans.every(s=>s.status==='passed'));
  await fs.writeFile(path.join(run,'trace.json'),JSON.stringify(trace,null,2));
  await page.getByText('story writer',{exact:true}).waitFor();
  await page.screenshot({path:path.join(run,'01-generated-desktop.png'),fullPage:true});
  pass('All six workflow stages recorded and shown');
  await page.getByLabel('Reviewer name',{exact:true}).fill('Automated E2E fixture — not human review');
  await page.getByLabel('Review notes',{exact:true}).fill('Synthetic QA action only. Do not count this as human editorial review or training approval.');
  await reviewClick('Save and approve',401);
  pass('Missing reviewer credential rejected');
  await page.getByLabel('Reviewer key, if required',{exact:true}).fill(reviewerKey);
  await page.getByLabel(/^body$/i).fill('Mara gained 987654 places.');
  await reviewClick('Save and approve',422);
  pass('Unsupported numeric edit rejected');
  await page.getByLabel(/^body$/i).fill(story.body);
  await page.getByLabel(/^headline$/i).fill('A verified checkpoint update for Mara Velez.');
  await page.getByRole('checkbox').check();
  assert.equal(await page.getByRole('button',{name:'Save and approve',exact:true}).isDisabled(),true);
  await page.getByRole('checkbox').uncheck();
  pass('Training consent requires an explicit rights basis');
  const revised = await reviewClick('Save and approve',200);
  assert.equal(revised.review_revision,1);
  assert.equal(revised.status,'approved');
  const revisions = await (await context.request.get(`${api}/api/v1/stories/${story.id}/revisions`,{headers:{'X-Reviewer-Key':reviewerKey}})).json();
  assert.equal(revisions.length,1);
  assert.equal(revisions[0].before.headline,story.headline);
  assert.equal(revisions[0].after.headline,'A verified checkpoint update for Mara Velez.');
  assert.equal(revisions[0].training_consent,false);
  await fs.writeFile(path.join(run,'simulated-review-revisions.json'),JSON.stringify(revisions,null,2));
  pass('Simulated review persists original and edited text without training consent');
  const stale=await context.request.post(`${api}/api/v1/stories/${story.id}/review`,{headers:{'X-Reviewer-Key':reviewerKey},data:{decision:'rejected',reviewer:'Automated stale QA fixture',expected_revision:0}});
  assert.equal(stale.status(),409);
  pass('Stale concurrent review rejected');
  const unknown=await context.request.post(`${api}/api/v1/stories/generate`,{data:{race_id:'wser-demo',moment:{athlete_bib:'999',signal_type:'position_gain',headline_hint:'Unknown athlete'}}});
  assert.equal(unknown.status(),422);
  pass('Unknown athlete fails closed');
  const workflowResponse = page.waitForResponse(r=>r.url().endsWith('/evals/run'),{timeout:180000});
  await page.getByRole('button',{name:'Check workflow',exact:true}).click();
  const workflowReply = await workflowResponse;
  assert.equal(workflowReply.status(),200,await workflowReply.text());
  const workflow = await workflowReply.json();
  assert.ok(['PASS','FAIL'].includes(workflow.release_decision));
  assert.equal(workflow.case_results.length,6);
  assert.equal(workflow.release_decision,workflow.metrics.every(m=>m.passed)?'PASS':'FAIL');
  assert.equal(workflow.cases,6);
  assert.ok(workflow.suite.includes(expectedProvider));
  await fs.writeFile(path.join(run,'workflow-check.json'),JSON.stringify(workflow,null,2));
  pass('Check workflow reports every case and preserves model failures',{model_workflow_decision:workflow.release_decision,failed_model_cases:workflow.case_results.filter(c=>c.kind==='generation'&&!c.passed).length});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:path.join(run,'02-reviewed-mobile.png'),fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
  pass('Mobile Race Desk fits the viewport');
  const evidenceResponse=await page.goto(`${site}/week5`,{waitUntil:'networkidle'});
  assert.equal(evidenceResponse.status(),200);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
  pass('Week 5 page loads and fits mobile viewport');
  for(const file of ['UltraMedia_Week5_QLoRA.ipynb','synthetic-dataset.zip','SUBMISSION.md']){
    const download=await context.request.get(`${site}/week5/${file}`);
    assert.equal(download.status(),200);
    assert.ok((await download.body()).length>0);
  }
  pass('Notebook, dataset, and submission downloads are available');
  assert.deepEqual(report.page_errors,[]);
  report.passed=true;
} catch(error) {
  report.failure=error.message;
  await page.screenshot({path:path.join(run,'failure.png'),fullPage:true}).catch(()=>{});
  process.exitCode=1;
} finally {
  report.finished_at=new Date().toISOString();
  await context.close();
  await browser.close();
  await fs.writeFile(path.join(run,'e2e-report.json'),JSON.stringify(report,null,2));
  console.log(JSON.stringify({run,passed:report.passed,steps:report.steps.length,failure:report.failure}));
}
